package it.fast4x.riplay.extensions.experimental.appearancepreset.models

import androidx.compose.ui.graphics.Color
import it.fast4x.riplay.enums.AnimatedGradient
import it.fast4x.riplay.enums.BackgroundProgress
import it.fast4x.riplay.enums.CarouselSize
import it.fast4x.riplay.enums.ColorPaletteMode
import it.fast4x.riplay.enums.ColorPaletteName
import it.fast4x.riplay.enums.IconLikeType
import it.fast4x.riplay.enums.Languages
import it.fast4x.riplay.enums.LyricsAlignment
import it.fast4x.riplay.enums.LyricsBackground
import it.fast4x.riplay.enums.LyricsColor
import it.fast4x.riplay.enums.LyricsFontSize
import it.fast4x.riplay.enums.LyricsHighlight
import it.fast4x.riplay.enums.LyricsOutline
import it.fast4x.riplay.enums.MiniPlayerType
import it.fast4x.riplay.enums.NavigationBarPosition
import it.fast4x.riplay.enums.NotificationButtons
import it.fast4x.riplay.enums.PauseBetweenSongs
import it.fast4x.riplay.enums.PlayerBackgroundColors
import it.fast4x.riplay.enums.PlayerControlsType
import it.fast4x.riplay.enums.PlayerInfoType
import it.fast4x.riplay.enums.PlayerPlayButtonType
import it.fast4x.riplay.enums.PlayerThumbnailSize
import it.fast4x.riplay.enums.PlayerTimelineSize
import it.fast4x.riplay.enums.PlayerTimelineType
import it.fast4x.riplay.enums.PlayerType
import it.fast4x.riplay.enums.PrevNextSongs
import it.fast4x.riplay.enums.QueueLoopType
import it.fast4x.riplay.enums.QueueType
import it.fast4x.riplay.enums.Romanization
import it.fast4x.riplay.enums.SongsNumber
import it.fast4x.riplay.enums.SwipeAnimationNoThumbnail
import it.fast4x.riplay.enums.ThumbnailCoverType
import it.fast4x.riplay.enums.ThumbnailRoundness
import it.fast4x.riplay.enums.ThumbnailType
import it.fast4x.riplay.enums.WallpaperType
import it.fast4x.riplay.ui.styling.DefaultDarkColorPalette
import it.fast4x.riplay.ui.styling.DefaultLightColorPalette
import kotlinx.serialization.Serializable

@Serializable
data class AppearanceSettings(

    // PLAYER
    val showTopActionsBar: Boolean             = true,
    val showThumbnail: Boolean                 = true,
    val playerBackgroundColors: PlayerBackgroundColors = PlayerBackgroundColors.BlurredCoverColor,
    val blurStrength: Float                    = 25f,
    val thumbnailRoundness: ThumbnailRoundness = ThumbnailRoundness.None,
    val thumbnailType: ThumbnailType = ThumbnailType.Modern,
    val playerThumbnailSize: PlayerThumbnailSize = PlayerThumbnailSize.Biggest,
    val playerThumbnailSizeL: PlayerThumbnailSize = PlayerThumbnailSize.Biggest,
    val transparentBar: Boolean                = true,
    val bottomGradient: Boolean                = true,
    val expandedPlayer: Boolean                = true,
    val showLyricsThumbnail: Boolean           = false,
    val playerInfoType: PlayerInfoType = PlayerInfoType.Essential,
    val playerType: PlayerType = PlayerType.Essential,
    val playerTimelineType: PlayerTimelineType = PlayerTimelineType.Default,
    val playerTimelineSize: PlayerTimelineSize = PlayerTimelineSize.Biggest,
    val playerControlsType: PlayerControlsType = PlayerControlsType.Essential,
    val playerPlayButtonType: PlayerPlayButtonType = PlayerPlayButtonType.Disabled,
    val showTotalTimeQueue: Boolean            = false,
    val showRemainingSongTime: Boolean         = true,
    val showNextSongsInPlayer: Boolean         = false,
    val colorPaletteName: ColorPaletteName = ColorPaletteName.Dynamic,
    val colorPaletteMode: ColorPaletteMode = ColorPaletteMode.System,
    val transparentBackgroundActionBarPlayer: Boolean = true,
    val actionsSpacedEvenly: Boolean           = true,
    val showButtonPlayerVideo: Boolean         = false,
    val showButtonPlayerDiscover: Boolean      = false,
    val showButtonPlayerAddToPlaylist: Boolean = true,
    val showButtonPlayerLoop: Boolean          = false,
    val showButtonPlayerShuffle: Boolean       = true,
    val showButtonPlayerLyrics: Boolean        = false,
    val expandedPlayerToggle: Boolean          = false,
    val showButtonPlayerSleepTimer: Boolean    = false,
    val visualizerEnabled: Boolean             = false,
    val showButtonPlayerArrow: Boolean         = false,
    val showButtonPlayerStartRadio: Boolean    = false,
    val showButtonPlayerMenu: Boolean          = true,
    val showButtonPlayerSystemEqualizer: Boolean = false,
    val showBackgroundLyrics: Boolean          = false,
    val showPlayerActionsBar: Boolean          = true,
    val iconLikeType: IconLikeType             = IconLikeType.Essential,
    val playerSwapControlsWithTimeline: Boolean = false,
    val showvisthumbnail: Boolean              = false,
    val buttonzoomout: Boolean                 = false,
    val thumbnailpause: Boolean                = false,
    val showsongs: SongsNumber                 = SongsNumber.`2`,
    val showalbumcover: Boolean                = true,
    val prevNextSongs: PrevNextSongs           = PrevNextSongs.twosongs,
    val tapqueue: Boolean                      = true,
    val swipeUpQueue: Boolean                  = true,
    val statsfornerds: Boolean                 = false,
    val queueType: QueueType                   = QueueType.Modern,
    val noblur: Boolean                        = true,
    val fadingedge: Boolean                    = false,
    val carousel: Boolean                      = true,
    val carouselSize: CarouselSize             = CarouselSize.Biggest,
    val keepPlayerMinimized: Boolean           = false,
    val playerInfoShowIcons: Boolean           = true,
    val queueDurationExpanded: Boolean         = true,
    val titleExpanded: Boolean                 = true,
    val timelineExpanded: Boolean              = true,
    val controlsExpanded: Boolean              = true,
    val miniQueueExpanded: Boolean             = true,
    val statsExpanded: Boolean                 = true,
    val actionExpanded: Boolean                = true,
    val showCoverThumbnailAnimation: Boolean   = false,
    val coverThumbnailAnimation: ThumbnailCoverType = ThumbnailCoverType.Vinyl,
    val topPadding: Boolean                    = true,
    val animatedGradient: AnimatedGradient     = AnimatedGradient.Linear,
    val albumCoverRotation: Boolean            = false,
    val thumbnailFadeEx: Float                 = 5f,
    val thumbnailFade: Float                   = 5f,
    val thumbnailSpacing: Float                = 0f,
    val thumbnailSpacingL: Float               = 0f,
    val imageCoverSize: Float                  = 50f,
    val blurDarkenFactor: Float                = 0.5f,
    val blackgradient: Boolean                 = false,
    val textoutline: Boolean                   = false,
    val disablePlayerHorizontalSwipe: Boolean  = false,
    val showLikeButtonBackgroundPlayer: Boolean = true,
    val isShowingThumbnailInLockscreen: Boolean = true,
    val lastPlayerPlayButtonType: PlayerPlayButtonType = PlayerPlayButtonType.Rectangular,
    val disableScrollingText: Boolean           = false,
    val seekWithTap: Boolean                   = false,
    val thumbnailTapEnabled: Boolean            = true,
    val navigationBarPosition: NavigationBarPosition = NavigationBarPosition.Bottom,
    val isGradientBackgroundEnabled: Boolean   = false,
    val backgroundProgress: BackgroundProgress = BackgroundProgress.MiniPlayer,
    val clickLyricsText: Boolean               = true,
    val miniPlayerType: MiniPlayerType = MiniPlayerType.Modern,
    val playerEnableLyricsPopupMessage: Boolean = true,
    val notificationPlayerFirstIcon: NotificationButtons = NotificationButtons.Repeat,
    val notificationPlayerSecondIcon: NotificationButtons = NotificationButtons.Favorites,
    val enableWallpaper: Boolean               = false,
    val wallpaperType: WallpaperType           = WallpaperType.Lockscreen,
    val swipeAnimationNoThumbnail: SwipeAnimationNoThumbnail     = SwipeAnimationNoThumbnail.Sliding,
    val queueLoopType: QueueLoopType                 = QueueLoopType.Default,
    val discoverIsEnabled: Boolean                 = false,
    val playlistIndicator: Boolean                 = false,
    val extraSpace: Boolean                        = false,
    val jumpPrevious: String                          = "3",
    val lyricsColor: LyricsColor                   = LyricsColor.Thememode,
    val lyricsOutline: LyricsOutline                = LyricsOutline.None,
    val lyricsBackground: LyricsBackground          = LyricsBackground.Black,
    val lyricsFontSize: LyricsFontSize              = LyricsFontSize.Medium,
    val lyricsHighlight: LyricsHighlight            = LyricsHighlight.None,
    val lyricsAlignment: LyricsAlignment            = LyricsAlignment.Center,
    val lyricsSizeAnimate: Boolean                  = false,
    val lyricsSize: Float                           = 20f,
    val lyricsSizeL: Float                          = 20f,
    val romanization: Romanization                  = Romanization.Off,
    val showSecondLine: Boolean                    = false,
    val landscapeControls: Boolean                 = true,
    val isShowingSynchronizedLyrics: Boolean       = false,
    val isShowingSynchronizedWordByWordLyrics: Boolean = false,
    val customColor: Int                            = Color.Green.hashCode(),
    val lastPlayerTimelineType: PlayerTimelineType = PlayerTimelineType.Default,
    val lastPlayerThumbnailSize: PlayerThumbnailSize = PlayerThumbnailSize.Biggest,
    val lastPlayerThumbnailSizeL: PlayerThumbnailSize = PlayerThumbnailSize.Biggest,
    val customThemeLight_Background0: Int           = DefaultLightColorPalette.background0.hashCode(),
    val customThemeLight_Background1: Int           = DefaultLightColorPalette.background1.hashCode(),
    val customThemeLight_Background2: Int           = DefaultLightColorPalette.background2.hashCode(),
    val customThemeLight_Background3: Int           = DefaultLightColorPalette.background3.hashCode(),
    val customThemeLight_Background4: Int           = DefaultLightColorPalette.background4.hashCode(),
    val customThemeLight_Text: Int                  = DefaultLightColorPalette.text.hashCode(),
    val customThemeLight_TextSecondary: Int         = DefaultLightColorPalette.textSecondary.hashCode(),
    val customThemeLight_TextDisabled: Int          = DefaultLightColorPalette.textDisabled.hashCode(),
    val customThemeLight_IconButtonPlayer: Int      = DefaultLightColorPalette.iconButtonPlayer.hashCode(),
    val customThemeLight_Accent: Int                = DefaultLightColorPalette.accent.hashCode(),
    val customThemeDark_Background0: Int            = DefaultDarkColorPalette.background0.hashCode(),
    val customThemeDark_Background1: Int            = DefaultDarkColorPalette.background1.hashCode(),
    val customThemeDark_Background2: Int            = DefaultDarkColorPalette.background2.hashCode(),
    val customThemeDark_Background3: Int            = DefaultDarkColorPalette.background3.hashCode(),
    val customThemeDark_Background4: Int            = DefaultDarkColorPalette.background4.hashCode(),
    val customThemeDark_Text: Int                   = DefaultDarkColorPalette.text.hashCode(),
    val customThemeDark_TextSecondary: Int          = DefaultDarkColorPalette.textSecondary.hashCode(),
    val customThemeDark_TextDisabled: Int           = DefaultDarkColorPalette.textDisabled.hashCode(),
    val customThemeDark_IconButtonPlayer: Int       = DefaultDarkColorPalette.iconButtonPlayer.hashCode(),
    val customThemeDark_Accent: Int                 = DefaultDarkColorPalette.accent.hashCode(),


    ) {
    companion object {

        val Aura = AppearanceSettings(
            showTopActionsBar = true,
            showThumbnail = true,
            playerBackgroundColors = PlayerBackgroundColors.BlurredCoverColor,
            blurStrength = 50f,
            thumbnailRoundness = ThumbnailRoundness.None,
            playerInfoType = PlayerInfoType.Essential,
            playerTimelineType = PlayerTimelineType.ThinBar,
            playerTimelineSize = PlayerTimelineSize.Biggest,
            playerControlsType = PlayerControlsType.Essential,
            playerPlayButtonType = PlayerPlayButtonType.Disabled,
            transparentBar = true,
            playerType = PlayerType.Essential,
            showLyricsThumbnail = false,
            expandedPlayer = true,
            thumbnailType = ThumbnailType.Modern,
            playerThumbnailSize = PlayerThumbnailSize.Big,
            showTotalTimeQueue = false,
            bottomGradient = true,
            showRemainingSongTime = true,
            showNextSongsInPlayer = false,
            colorPaletteName = ColorPaletteName.Dynamic,
            colorPaletteMode = ColorPaletteMode.System,
            transparentBackgroundActionBarPlayer = true,
            actionsSpacedEvenly = true,
            showButtonPlayerVideo = false,
            showButtonPlayerDiscover = false,
            showButtonPlayerAddToPlaylist = true,
            showButtonPlayerLoop = false,
            showButtonPlayerShuffle = true,
            showButtonPlayerLyrics = false,
            expandedPlayerToggle = false,
            showButtonPlayerSleepTimer = false,
            visualizerEnabled = false,
            showButtonPlayerArrow = false,
            showButtonPlayerStartRadio = false,
            showButtonPlayerMenu = true,
            isShowingThumbnailInLockscreen = true
        )
        val Deck = AppearanceSettings(
            showTopActionsBar = true,
            showThumbnail = true,
            playerBackgroundColors = PlayerBackgroundColors.BlurredCoverColor,
            blurStrength = 50f,
            playerInfoType = PlayerInfoType.Essential,
            playerPlayButtonType = PlayerPlayButtonType.Disabled,
            playerTimelineType = PlayerTimelineType.ThinBar,
            playerControlsType = PlayerControlsType.Essential,
            transparentBar = true,
            playerType = PlayerType.Modern,
            expandedPlayer = true,
            fadingedge = true,
            thumbnailFadeEx = 4f,
            thumbnailSpacing = -32f,
            thumbnailType = ThumbnailType.Essential,
            carouselSize = CarouselSize.Big,
            playerThumbnailSize = PlayerThumbnailSize.Biggest,
            showTotalTimeQueue = false,
            transparentBackgroundActionBarPlayer = true,
            showRemainingSongTime = true,
            bottomGradient = true,
            showLyricsThumbnail = false,
            thumbnailRoundness = ThumbnailRoundness.Medium,
            showNextSongsInPlayer = true,
            colorPaletteName = ColorPaletteName.ModernBlack,
            colorPaletteMode = ColorPaletteMode.System,
            actionsSpacedEvenly = true,
            showButtonPlayerVideo = false,
            showButtonPlayerDiscover = false,
            showButtonPlayerAddToPlaylist = true,
            showButtonPlayerLoop = false,
            showButtonPlayerShuffle = false,
            showButtonPlayerLyrics = false,
            expandedPlayerToggle = true,
            showButtonPlayerSleepTimer = false,
            visualizerEnabled = false,
            showButtonPlayerArrow = false,
            showButtonPlayerStartRadio = false,
            showButtonPlayerMenu = true,
            isShowingThumbnailInLockscreen = true
        )

        val Zen = AppearanceSettings(
            showTopActionsBar = false,
            showThumbnail = false,
            noblur = true,
            topPadding = false,
            playerBackgroundColors = PlayerBackgroundColors.BlurredCoverColor,
            blurStrength = 50f,
            playerPlayButtonType = PlayerPlayButtonType.Disabled,
            playerInfoType = PlayerInfoType.Modern,
            playerInfoShowIcons = false,
            playerTimelineType = PlayerTimelineType.ThinBar,
            playerControlsType = PlayerControlsType.Essential,
            transparentBar = true,
            playerType = PlayerType.Modern,
            expandedPlayer = true,
            showTotalTimeQueue = false,
            transparentBackgroundActionBarPlayer = true,
            showRemainingSongTime = true,
            bottomGradient = true,
            showLyricsThumbnail = false,
            showNextSongsInPlayer = false,
            colorPaletteName = ColorPaletteName.Dynamic,
            colorPaletteMode = ColorPaletteMode.Dark,
            actionsSpacedEvenly = true,
            showButtonPlayerVideo = false,
            showButtonPlayerDiscover = false,
            showButtonPlayerAddToPlaylist = false,
            showButtonPlayerLoop = false,
            showButtonPlayerShuffle = false,
            showButtonPlayerLyrics = false,
            expandedPlayerToggle = false,
            showButtonPlayerSleepTimer = false,
            visualizerEnabled = false,
            showButtonPlayerArrow = false,
            showButtonPlayerStartRadio = false,
            showButtonPlayerMenu = true,
            isShowingThumbnailInLockscreen = true
        )

        val Noir = AppearanceSettings(
            showTopActionsBar = false,
            topPadding = false,
            showThumbnail = true,
            playerBackgroundColors = PlayerBackgroundColors.BlurredCoverColor,
            blurStrength = 50f,
            playerInfoType = PlayerInfoType.Essential,
            playerTimelineType = PlayerTimelineType.FakeAudioBar,
            playerTimelineSize = PlayerTimelineSize.Biggest,
            playerControlsType = PlayerControlsType.Modern,
            playerPlayButtonType = PlayerPlayButtonType.Disabled,
            colorPaletteName = ColorPaletteName.PureBlack,
            colorPaletteMode = ColorPaletteMode.Dark,
            transparentBar = false,
            expandedPlayer = false,
            playerThumbnailSize = PlayerThumbnailSize.Expanded,
            showTotalTimeQueue = false,
            transparentBackgroundActionBarPlayer = true,
            showRemainingSongTime = true,
            bottomGradient = true,
            showLyricsThumbnail = false,
            thumbnailType = ThumbnailType.Essential,
            thumbnailRoundness = ThumbnailRoundness.Light,
            playerType = PlayerType.Modern,
            fadingedge = true,
            thumbnailFade = 5f,
            showNextSongsInPlayer = false,
            actionsSpacedEvenly = true,
            showButtonPlayerVideo = false,
            showButtonPlayerDiscover = false,
            showButtonPlayerAddToPlaylist = false,
            showButtonPlayerLoop = true,
            showButtonPlayerShuffle = true,
            showButtonPlayerLyrics = false,
            expandedPlayerToggle = false,
            showButtonPlayerSleepTimer = false,
            visualizerEnabled = false,
            showButtonPlayerArrow = true,
            showButtonPlayerStartRadio = false,
            showButtonPlayerMenu = true,
            isShowingThumbnailInLockscreen = true
        )

        val Prism = AppearanceSettings(
            showTopActionsBar = false,
            topPadding = true,
            showThumbnail = true,
            playerBackgroundColors = PlayerBackgroundColors.AnimatedGradient,
            animatedGradient = AnimatedGradient.Linear,
            playerInfoType = PlayerInfoType.Essential,
            playerTimelineType = PlayerTimelineType.PinBar,
            playerTimelineSize = PlayerTimelineSize.Biggest,
            playerControlsType = PlayerControlsType.Essential,
            playerPlayButtonType = PlayerPlayButtonType.Square,
            colorPaletteName = ColorPaletteName.Dynamic,
            colorPaletteMode = ColorPaletteMode.PitchBlack,
            transparentBar = false,
            playerType = PlayerType.Modern,
            expandedPlayer = false,
            playerThumbnailSize = PlayerThumbnailSize.Biggest,
            showTotalTimeQueue = false,
            transparentBackgroundActionBarPlayer = true,
            showRemainingSongTime = true,
            showLyricsThumbnail = false,
            thumbnailType = ThumbnailType.Modern,
            thumbnailRoundness = ThumbnailRoundness.Light,
            fadingedge = true,
            thumbnailFade = 0f,
            thumbnailFadeEx = 5f,
            thumbnailSpacing = -32f,
            showNextSongsInPlayer = false,
            actionsSpacedEvenly = true,
            showButtonPlayerVideo = false,
            showButtonPlayerDiscover = false,
            showButtonPlayerAddToPlaylist = false,
            showButtonPlayerLoop = false,
            showButtonPlayerShuffle = false,
            showButtonPlayerLyrics = false,
            expandedPlayerToggle = true,
            showButtonPlayerSleepTimer = false,
            visualizerEnabled = false,
            showButtonPlayerArrow = false,
            showButtonPlayerStartRadio = false,
            showButtonPlayerMenu = true,
            isShowingThumbnailInLockscreen = true
        )

        val Groove = AppearanceSettings(
            showTopActionsBar = true,
            showThumbnail = true,
            playerBackgroundColors = PlayerBackgroundColors.CoverColorGradient,
            playerInfoType = PlayerInfoType.Essential,
            playerTimelineType = PlayerTimelineType.Wavy,
            playerTimelineSize = PlayerTimelineSize.Biggest,
            playerControlsType = PlayerControlsType.Essential,
            playerPlayButtonType = PlayerPlayButtonType.CircularRibbed,
            colorPaletteName = ColorPaletteName.Dynamic,
            colorPaletteMode = ColorPaletteMode.Dark,
            transparentBar = false,
            playerType = PlayerType.Essential,
            expandedPlayer = true,
            playerThumbnailSize = PlayerThumbnailSize.Big,
            showTotalTimeQueue = false,
            transparentBackgroundActionBarPlayer = true,
            showRemainingSongTime = true,
            showLyricsThumbnail = false,
            thumbnailType = ThumbnailType.Modern,
            thumbnailRoundness = ThumbnailRoundness.Light,
            showNextSongsInPlayer = false,
            actionsSpacedEvenly = true,
            showButtonPlayerVideo = false,
            showButtonPlayerDiscover = false,
            showButtonPlayerAddToPlaylist = false,
            showButtonPlayerLoop = false,
            showButtonPlayerShuffle = true,
            showButtonPlayerLyrics = true,
            expandedPlayerToggle = false,
            showButtonPlayerSleepTimer = false,
            visualizerEnabled = false,
            showButtonPlayerArrow = false,
            showButtonPlayerStartRadio = false,
            showButtonPlayerMenu = true,
            isShowingThumbnailInLockscreen = true
        )

    }
}