name: Build Metrics Card

on:
  schedule:
    - cron: '0 0 * * *' # Si aggiorna automaticamente ogni giorno
  workflow_dispatch: # Ti permette di aggiornarlo a mano

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          # Diciamo di non mostrare il profilo base, solo i plugin
          base: ""
        env:
          # Qui passiamo i comandi dei download come variabili d'ambiente
          # In questo modo GitHub Actions non li blocca!
          METRICS_PLUGIN_DOWNLOADS: "yes"
          METRICS_PLUGIN_DOWNLOADS_SECTIONS: "total,latest"
          METRICS_PLUGIN_DOWNLOADS_UPLOADS: "yes"
